# Generated by Django 3.2.5 on 2021-07-14 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Área de Salud')),
            ],
            options={
                'verbose_name': 'Área de Salud',
                'verbose_name_plural': 'Área de Salud',
                'db_table': 'anticuerpos_sld_area_salud',
            },
        ),
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Condición')),
            ],
            options={
                'verbose_name': 'Condición',
                'verbose_name_plural': 'Condición',
                'db_table': 'anticuerpos_sld_condicion',
                'unique_together': {('nombre',)},
            },
        ),
        migrations.CreateModel(
            name='LabEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Laboratorio de envío')),
            ],
            options={
                'verbose_name': 'Laboratorio de envío',
                'verbose_name_plural': 'Laboratorio de envío',
                'db_table': 'anticuerpos_sld_lab_envio',
                'unique_together': {('nombre',)},
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Municipios')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'anticuerpos_sld_municipios',
            },
        ),
        migrations.CreateModel(
            name='TipoTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Tipo Test')),
            ],
            options={
                'verbose_name': 'Tipo de Test',
                'verbose_name_plural': 'Tipo de Test',
                'db_table': 'anticuerpos_sld_tipo_test',
                'unique_together': {('nombre',)},
            },
        ),
        migrations.CreateModel(
            name='TipoMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Tipo de muestra')),
            ],
            options={
                'verbose_name': 'Tipo de muestra',
                'verbose_name_plural': 'Tipo de muestras',
                'db_table': 'anticuerpos_sld_tipo_muestra',
                'unique_together': {('nombre',)},
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'anticuerpos_sld_provincias',
                'unique_together': {('nombre',)},
            },
        ),
        migrations.CreateModel(
            name='ProcedenciaMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Procedencia de muestra')),
            ],
            options={
                'verbose_name': 'Procedencia de muestra',
                'verbose_name_plural': 'Procedencia de las muestras',
                'db_table': 'anticuerpos_sld_procedencia_muestra',
                'unique_together': {('nombre',)},
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noCorridas', models.CharField(blank=True, max_length=150, null=True, verbose_name='No. Corrida')),
                ('codigo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Código')),
                ('idSuma', models.CharField(blank=True, max_length=150, null=True, verbose_name='ID SUMA')),
                ('idLab', models.CharField(blank=True, max_length=150, null=True, verbose_name='ID. Lab')),
                ('nombresApellidos', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombres y Apellidos')),
                ('edad', models.BigIntegerField(blank=True, null=True, verbose_name='Edad')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=150, null=True, verbose_name='Sexo')),
                ('carIdentidad', models.CharField(blank=True, max_length=11, null=True, verbose_name='C Identidad/Pasaporte')),
                ('direccion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Dirección')),
                ('paisProcedencia', models.CharField(blank=True, max_length=150, null=True, verbose_name='País de Procedencia')),
                ('fis', models.DateField(blank=True, max_length=150, null=True, verbose_name='Fecha inicio de sintomas')),
                ('fecha', models.DateField(blank=True, max_length=150, null=True, verbose_name='Fecha toma de muestra')),
                ('fechaEnvio', models.DateField(blank=True, max_length=150, null=True, verbose_name='Fecha envío de la muestra')),
                ('resultado', models.CharField(blank=True, choices=[('negativo', 'Negativo'), ('positivo', 'Positivo')], max_length=150, null=True, verbose_name='Resultado')),
                ('fechaRecibido', models.DateField(blank=True, max_length=150, null=True, verbose_name='Fecha de recibido')),
                ('observacion', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Observaciones')),
                ('areaSalud', models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.PROTECT, to='anticuerpos_sld_app.areasalud', verbose_name='Área de salud')),
                ('condicion', models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.PROTECT, to='anticuerpos_sld_app.condicion')),
                ('labEnvio', models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.PROTECT, to='anticuerpos_sld_app.labenvio', verbose_name='Laboratorio de envío')),
                ('municipio', models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.PROTECT, to='anticuerpos_sld_app.municipio')),
                ('procMuestra', models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.PROTECT, to='anticuerpos_sld_app.procedenciamuestra', verbose_name='Procedencia de muestra')),
                ('provincia', models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.PROTECT, to='anticuerpos_sld_app.provincia')),
                ('tipoMuestra', models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.PROTECT, to='anticuerpos_sld_app.tipomuestra', verbose_name='Tipo de muestra')),
                ('tipoTest', models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.PROTECT, to='anticuerpos_sld_app.tipotest', verbose_name='Tipo de Test')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente_sld_datos',
            },
        ),
        migrations.AddField(
            model_name='municipio',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anticuerpos_sld_app.provincia'),
        ),
        migrations.AddField(
            model_name='areasalud',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anticuerpos_sld_app.municipio'),
        ),
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='areasalud',
            unique_together={('nombre',)},
        ),
    ]
