# Generated by Django 3.2.5 on 2021-07-24 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anticuerpos_sld_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='condicion',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.PROTECT, to='anticuerpos_sld_app.condicion', verbose_name='Condición'),
        ),
        migrations.CreateModel(
            name='ClasificacionPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Clasificación Paciente')),
            ],
            options={
                'verbose_name': 'Clasificación Paciente',
                'verbose_name_plural': 'Clasificación Paciente',
                'db_table': 'anticuerpos_sld_clasificacion_paciente',
                'unique_together': {('nombre',)},
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='clasificacionPaciente',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.PROTECT, to='anticuerpos_sld_app.clasificacionpaciente', verbose_name='Clasificación Paciente'),
        ),
    ]
