# Generated by Django 3.2.5 on 2021-07-24 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anticuerpos_sld_app', '0002_auto_20210723_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'db_table': 'anticuerpos_sld_resultado',
                'unique_together': {('nombre',)},
            },
        ),
        migrations.AlterField(
            model_name='paciente',
            name='resultado',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.PROTECT, to='anticuerpos_sld_app.resultado', verbose_name='Resultado'),
        ),
    ]
