# Generated by Django 3.2.5 on 2021-08-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticuerpos_sld_app', '0003_auto_20210723_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cancer',
            field=models.BooleanField(default=False, verbose_name='Cáncer'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cardioIs',
            field=models.BooleanField(default=False, verbose_name='Cardiopatía Isquémica'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='diabetis',
            field=models.BooleanField(default=False, verbose_name='Diabetes Mellitus'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='epoc',
            field=models.BooleanField(default=False, verbose_name='EPOC'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='hiperArt',
            field=models.BooleanField(default=False, verbose_name='Hipertensión Arterial'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='insuCard',
            field=models.BooleanField(default=False, verbose_name='Insuficiencia cardiaca'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='obesidad',
            field=models.BooleanField(default=False, verbose_name='Obesidad'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='otras',
            field=models.BooleanField(default=False, verbose_name='Otras'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='renalCro',
            field=models.BooleanField(default=False, verbose_name='Enfermedad renal crónica'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='carIdentidad',
            field=models.CharField(default=0, max_length=11, verbose_name='C Identidad/Pasaporte'),
        ),
        migrations.AlterUniqueTogether(
            name='paciente',
            unique_together={('tipoTest', 'carIdentidad', 'fis')},
        ),
    ]
